scalar Date

type Product {
  id: ID!
  name: String!
  slug: String!
  description: String!
  category: Category!
  brand: Brand
  price: Float!
  discountPrice: Float
  stock: [Stock!]!
  material: String
  gender: String!
  images: [Image!]
  tags: [String!]
  status: String!
  sku: String!
  createdAt: Date!
  updatedAt: Date!
}

type Category {
  id: ID!
  name: String!
}

type Brand {
  id: ID!
  name: String!
}

type Stock {
  size: String!
  color: String!
  quantity: Int!
}

type Image {
  url: String!
  alt: String
}

input CreateProductInput {
  name: String!
  slug: String!
  description: String!
  categoryId: ID!
  brand: BrandInput
  price: Float!
  discountPrice: Float
  stock: [StockInput!]!
  material: String
  gender: String!
  images: [ImageInput!]
  tags: [String!]
  status: String!
  sku: String!
}

input BrandInput {
  id: ID!
  name: String!
}

input StockInput {
  size: String!
  color: String!
  quantity: Int!
}

input ImageInput {
  url: String!
  alt: String
}
